services:
  certbot-nginx-server:
    build: .
    image: certbot-nginx-server
    container_name: certbot-nginx-server
    env_file:
      - .env
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/.well-known/acme-challenge:/var/www/certbot/.well-known/acme-challenge/
      - ./logs/nginx:/var/log/nginx
      - ./logs/letsencrypt:/var/log/letsencrypt
    ports:
      - ${EXTERNAL_PORT_HTTP}:80
